name: token_theme_kit
description: "A Flutter theming package that applies design tokens to generate consistent, scalable Material themes across your entire app."
version: 0.0.1

repository: https://github.com/shahriarhu/token_theme_kit
homepage: https://github.com/shahriarhu/token_theme_kit

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
